### ISSUE TITLE
[CRASH] Crash on startup.

### ISSUE THREAD

**Issue by ghost** [Codetoil/HaveASolTime#1]
![Screenshot 2024-05-17 123415](https://github.com/Codetoil/HaveASolTime/assets/166317640/3e6a0a42-9266-4342-8aa0-ea70ee6b6e42)

**Comment by ghost** [comment]
I'm working on a Kerbal Space Program themed Galacticraft modpack, and I want to be able to land on Sun/Kerbol. And I keep getting this odd crash.

**Comment by Codetoil** [comment]
The mod hasn't been ported to Galacticraft 4.0.6, so if that's that then that's why it crashed.
If you want any more detail than this I'll need the logs.

**Comment by ghost** [comment]
> The mod hasn't been ported to Galacticraft 4.0.6, so if that's that then that's why it crashed. If you want any more detail than this I'll need the logs.

What version can i use?

**Comment by Codetoil** [comment]
4.0.5 should work

**Comment by ghost** [comment]
> 4.0.5 should work

![Screenshot 2024-05-21 200235](https://github.com/Codetoil/HaveASolTime/assets/166317640/c3c1a941-23a9-4956-a1b7-b6080e5b423d)

**Comment by Codetoil** [comment]
Ok, looks like this is a bigger error than I was expecting. I'm going to need the crash reports and debug logs.

**Comment by ghost** [comment]
> Ok, looks like this is a bigger error than I was expecting. I'm going to need the crash reports and debug logs.
15:08:55.338
game
at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_51]
15:08:55.338
game
at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:594) ~[forge-1.12.2-14.23.5.2859.jar:?]
15:08:55.338
game
at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:451) ~[forge-1.12.2-14.23.5.2859.jar:?]
15:08:55.338
game
at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265) ~[forge-1.12.2-14.23.5.2859.jar:?]
15:08:55.338
game
at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) ~[forge-1.12.2-14.23.5.2859.jar:?]
15:08:55.338
game
... 5 more
15:08:55.338
game
Exception in thread "main" [15:08:55] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
15:08:55.338
game
[15:08:55] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
15:08:55.338
game
[15:08:55] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
15:08:55.338
game
[15:08:55] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:107)
15:08:55.339
game
[15:08:55] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:971)
15:08:55.339
game
[15:08:55] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
15:08:55.339
game
[15:08:55] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
15:08:55.377
monitor
Process Monitor
Process crashed with exit code 1

**Comment by ghost** [comment]
15:08:54.427
launcher
main
Version does not support log configuration, will assume one plaintext entry per line
15:08:55.173
game
[15:08:55] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
15:08:55.180
game
[15:08:55] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
15:08:55.182
game
[15:08:55] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
15:08:55.196
game
[15:08:55] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2859 for Minecraft 1.12.2 loading
15:08:55.196
game
[15:08:55] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at C:\Users\catfi\curseforge\minecraft\Install\runtime\jre-legacy\windows-x64\jre-legacy
15:08:55.255
game
[15:08:55] [main/INFO] [FML]: Searching C:\Users\catfi\curseforge\minecraft\Instances\g\mods for mods
15:08:55.261
game
[15:08:55] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from !mixinbooter-8.8.jar
15:08:55.268
game
[15:08:55] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in Galacticraft-1.12.2-4.0.5.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
15:08:55.314
game
[15:08:55] [main/WARN] [FML]: The coremod MicdoodlePlugin (micdoodle8.mods.miccore.MicdoodlePlugin) is not signed!
15:08:55.315
game
[15:08:55] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in tothestars-0.1.1.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
15:08:55.317
game
[15:08:55] [main/WARN] [FML]: The coremod TTSCoremod (io.github.codetoil.tothestars.asm.TTSCoremod) is not signed!
15:08:55.337
game
[15:08:55] [main/ERROR] [LaunchWrapper]: Unable to launch
15:08:55.337
game
java.lang.RuntimeException: An error occurred trying to configure the Minecraft home at C:\Users\catfi\curseforge\minecraft\Instances\g for Forge Mod Loader
15:08:55.337
game
at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:111) ~[forge-1.12.2-14.23.5.2859.jar:?]

**Comment by Codetoil** [comment]
Moving this to here:
https://github.com/Codetoil/tothestars/issues/2
